### PR TITLE
Use non-deprecated GPL-3.0-only license tag

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Comment by maximiliankolb** [comment]
LGTM:

image

**Comment by nadjaheitmann** [comment]
Not sure what is wrong with the tests again, though. Maybe Rails 7, but the error about a missing file looks strange.

**Comment by maximiliankolb** [comment]
@nadjaheitmann Second commit LGTM. Did you base the first commit on https://spdx.org/licenses/?

**Comment by nadjaheitmann** [comment]
> @nadjaheitmann Second commit LGTM. Did you base the first commit on https://spdx.org/licenses/?

Yeah, I have already seen the licence tag change in a couple of other Foreman plugins. E.g. https://github.com/theforeman/hammer-cli-foreman-ansible/blob/master/hammer_cli_foreman_ansible.gemspec  . Mostly hammer plugins, actually :thinking:

**Pull request merged**
