### PR TITLE
Change README for foreman-installer support

### PR DESCRIPTION
**Pull request by dgoetz**
Depends on https://github.com/theforeman/foreman-installer/pull/782, so do not this one merge before it was merged to the installer and a new installer release was published, but I wanted to create the PR already for completeness.

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@dgoetz Thank you, this is a very cool improvement!

**Comment by m-bucher** [comment]
Thanks @dgoetz, could you add a note of the foreman(-installer)-version the parameter is introduced in?

**Comment by dgoetz** [comment]
It is merged now, to add the version correctly I have to wait for the next installer release which should land soon (guessing by the activity in the repository).

**Comment by dgoetz** [comment]
I added the version of Foreman / Katello to the README since it is out now.

**Comment by m-bucher** [comment]
Great, thanks @dgoetz

**Pull request merged**
